// GENERATED CODE - DO NOT EDIT BY HAND
// Generated by scripts/generate-cross-platform-tokens.mjs in unierp-design-system

import 'package:flutter/material.dart';

class UniTokens {
  // Colors
  static const Color primary = Color(0xFF3B82F6);
  static const Color primaryLight = Color(0xFFE0E7FF);
  static const Color secondary = Color(0xFF64748B);
  static const Color success = Color(0xFF22C55E);
  static const Color warning = Color(0xFFEAB308);
  static const Color danger = Color(0xFFEF4444);
  static const Color background = Color(0xFFFFFFFF);
  static const Color bgElevated = Color(0xFFFFFFFF);
  static const Color bgSunken = Color(0xFFF8FAFC);
  static const Color border = Color(0xFFE2E8F0);
  static const Color text = Color(0xFF0F172A);
  static const Color textSecondary = Color(0xFF475569);
  static const Color textMuted = Color(0xFF94A3B8);

  // Spacing
  static const double spaceXs = 4.0;
  static const double spaceSm = 8.0;
  static const double spaceMd = 16.0;
  static const double spaceLg = 24.0;
  static const double spaceXl = 32.0;

  // Radius
  static const double radiusSm = 4.0;
  static const double radiusMd = 8.0;
  static const double radiusLg = 12.0;
}
