// GENERATED CODE — DO NOT EDIT BY HAND.
// Generated by scripts/generate-cross-platform-tokens.mjs in unierp-design-system
// from src/tokens/themes/strata{,-dark}.css. Re-run that script after any
// token change; `--check` fails CI when this file has drifted.
//
// UI_UX_BRIEF §9: "Native mobile (Flutter): same tokens, platform-native
// navigation and gestures." Same tokens means these are DERIVED, never typed.

import 'package:flutter/material.dart';

class UniTokens {
  const UniTokens._();

  static const Color primary = Color(0xFF1D4ED8);
  static const Color onPrimary = Color(0xFFFFFFFF);
  static const Color primaryLight = Color(0xFFEFF6FF);
  static const Color success = Color(0xFF15803D);
  static const Color successLight = Color(0xFFF0FDF4);
  static const Color successText = Color(0xFF14532D);
  static const Color warning = Color(0xFFB45309);
  static const Color warningLight = Color(0xFFFFFBEB);
  static const Color warningText = Color(0xFF78350F);
  static const Color danger = Color(0xFFB91C1C);
  static const Color dangerLight = Color(0xFFFEF2F2);
  static const Color dangerText = Color(0xFF7F1D1D);
  static const Color info = Color(0xFF0369A1);
  static const Color background = Color(0xFFF8FAFC);
  static const Color bgElevated = Color(0xFFFFFFFF);
  static const Color bgSunken = Color(0xFFF1F5F9);
  static const Color border = Color(0xFFE2E8F0);
  static const Color borderStrong = Color(0xFF64748B);
  static const Color borderFocus = Color(0xFF2563EB);
  static const Color text = Color(0xFF0F172A);
  static const Color textSecondary = Color(0xFF334155);
  static const Color textTertiary = Color(0xFF475569);
  static const Color scopeApp = Color(0xFF1D4ED8);
  static const Color scopeSite = Color(0xFF0F766E);
  static const Color scopeLibrary = Color(0xFFB45309);
  static const Color scopeManage = Color(0xFF475569);
  // Legacy scale aliases — see LEGACY_ALIASES in the generator.
  static const double spaceXs = 4.0;
  static const double spaceSm = 8.0;
  static const double spaceMd = 16.0;
  static const double spaceLg = 24.0;
  static const double spaceXl = 32.0;
  static const double radiusSm = 2.0;
  static const double radiusMd = 4.0;
  static const double radiusLg = 6.0;
}

class UniTokensDark {
  const UniTokensDark._();

  static const Color primary = Color(0xFF38BDF8);
  static const Color onPrimary = Color(0xFF09090B);
  static const Color primaryLight = Color(0xFF082F49);
  static const Color success = Color(0xFF4ADE80);
  static const Color successLight = Color(0xFF052E16);
  static const Color successText = Color(0xFF86EFAC);
  static const Color warning = Color(0xFFFBBF24);
  static const Color warningLight = Color(0xFF451A03);
  static const Color warningText = Color(0xFFFDE68A);
  static const Color danger = Color(0xFFF87171);
  static const Color dangerLight = Color(0xFF450A0A);
  static const Color dangerText = Color(0xFFFCA5A5);
  static const Color info = Color(0xFF60A5FA);
  static const Color background = Color(0xFF09090B);
  static const Color bgElevated = Color(0xFF18181B);
  static const Color bgSunken = Color(0xFF0C0E12);
  static const Color border = Color(0xFF27272A);
  static const Color borderStrong = Color(0xFF71717A);
  static const Color borderFocus = Color(0xFF38BDF8);
  static const Color text = Color(0xFFF4F4F5);
  static const Color textSecondary = Color(0xFFA1A1AA);
  static const Color textTertiary = Color(0xFF9CA3AF);
  static const Color scopeApp = Color(0xFF38BDF8);
  static const Color scopeSite = Color(0xFF2DD4BF);
  static const Color scopeLibrary = Color(0xFFFBBF24);
  static const Color scopeManage = Color(0xFF94A3B8);
}

class UniScale {
  const UniScale._();

  // Spacing
  static const double space1 = 4.0;
  static const double space2 = 8.0;
  static const double space3 = 12.0;
  static const double space4 = 16.0;
  static const double space5 = 20.0;
  static const double space6 = 24.0;
  static const double space8 = 32.0;

  // Radius
  static const double radiusSm = 2.0;
  static const double radiusMd = 4.0;
  static const double radiusLg = 6.0;
  static const double radiusXl = 8.0;

  // Type
  static const double textXs = 12.0;
  static const double textSm = 14.0;
  static const double textBase = 16.0;
  static const double textLg = 18.0;
  static const double textXl = 20.0;

  // Touch
  static const double minTouchTarget = 44.0;
}
