// GENERATED CODE — DO NOT EDIT BY HAND.
// Generated by scripts/generate-cross-platform-tokens.mjs in unierp-design-system
// from src/tokens/themes/meridian{,-dark}.css. Re-run that script after any
// token change; `--check` fails CI when this file has drifted.
//
// UI_UX_BRIEF §9: "Native mobile (Flutter): same tokens, platform-native
// navigation and gestures." Same tokens means these are DERIVED, never typed.

import 'package:flutter/material.dart';

class UniTokens {
  const UniTokens._();

  static const Color primary = Color(0xFF0E6B75);
  static const Color onPrimary = Color(0xFFFFFFFF);
  static const Color primaryLight = Color(0xFFDCEDEF);
  static const Color success = Color(0xFF1F7A45);
  static const Color successLight = Color(0xFFE2F1E8);
  static const Color successText = Color(0xFF14512E);
  static const Color warning = Color(0xFFA15C07);
  static const Color warningLight = Color(0xFFFAEFDC);
  static const Color warningText = Color(0xFF6F3F04);
  static const Color danger = Color(0xFFB3121F);
  static const Color dangerLight = Color(0xFFFAE4E6);
  static const Color dangerText = Color(0xFF7D0B15);
  static const Color info = Color(0xFF4F53B8);
  static const Color background = Color(0xFFF7F6F4);
  static const Color bgElevated = Color(0xFFFFFFFF);
  static const Color bgSunken = Color(0xFFEEEDEA);
  static const Color border = Color(0xFFE2E0DB);
  static const Color borderStrong = Color(0xFF948F87);
  static const Color borderFocus = Color(0xFF0E6B75);
  static const Color text = Color(0xFF14191B);
  static const Color textSecondary = Color(0xFF4C5457);
  static const Color textTertiary = Color(0xFF626A6D);
  static const Color scopeApp = Color(0xFF0E6B75);
  static const Color scopeSite = Color(0xFF4F53B8);
  static const Color scopeLibrary = Color(0xFF8A6114);
  static const Color scopeManage = Color(0xFF4A5558);
  // Legacy scale aliases — see LEGACY_ALIASES in the generator.
  static const double spaceXs = 4.0;
  static const double spaceSm = 8.0;
  static const double spaceMd = 16.0;
  static const double spaceLg = 24.0;
  static const double spaceXl = 32.0;
  static const double radiusSm = 2.0;
  static const double radiusMd = 4.0;
  static const double radiusLg = 6.0;
}

class UniTokensDark {
  const UniTokensDark._();

  static const Color primary = Color(0xFF48C5CE);
  static const Color onPrimary = Color(0xFF04262B);
  static const Color primaryLight = Color(0xFF0F3538);
  static const Color success = Color(0xFF45B877);
  static const Color successLight = Color(0xFF10281A);
  static const Color successText = Color(0xFFA5E2BD);
  static const Color warning = Color(0xFFDFA040);
  static const Color warningLight = Color(0xFF2D2314);
  static const Color warningText = Color(0xFFF2D19F);
  static const Color danger = Color(0xFFE56A72);
  static const Color dangerLight = Color(0xFF2E1517);
  static const Color dangerText = Color(0xFFF5BCC0);
  static const Color info = Color(0xFF8B8FE0);
  static const Color background = Color(0xFF14171A);
  static const Color bgElevated = Color(0xFF1C2023);
  static const Color bgSunken = Color(0xFF0E1113);
  static const Color border = Color(0xFF2E3438);
  static const Color borderStrong = Color(0xFF6E7681);
  static const Color borderFocus = Color(0xFF48C5CE);
  static const Color text = Color(0xFFE6E3DE);
  static const Color textSecondary = Color(0xFFA3A29D);
  static const Color textTertiary = Color(0xFF949289);
  static const Color scopeApp = Color(0xFF48C5CE);
  static const Color scopeSite = Color(0xFF8B8FE0);
  static const Color scopeLibrary = Color(0xFFD9A441);
  static const Color scopeManage = Color(0xFF9AA5A8);
}

class UniScale {
  const UniScale._();

  // Spacing
  static const double space1 = 4.0;
  static const double space2 = 8.0;
  static const double space3 = 12.0;
  static const double space4 = 16.0;
  static const double space5 = 20.0;
  static const double space6 = 24.0;
  static const double space8 = 32.0;

  // Radius
  static const double radiusSm = 2.0;
  static const double radiusMd = 4.0;
  static const double radiusLg = 6.0;
  static const double radiusXl = 8.0;

  // Type
  static const double textXs = 12.0;
  static const double textSm = 14.0;
  static const double textBase = 16.0;
  static const double textLg = 18.0;
  static const double textXl = 20.0;

  // Touch
  static const double minTouchTarget = 44.0;
}
